# Build stage
FROM node:22-alpine AS builder
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./
COPY apps/service/package.json ./apps/service/
# COPY packages/*/package.json ./packages/

# Install dependencies
RUN pnpm install

# Copy source code
COPY . .

# Build backend
RUN cd apps/service && pnpm prisma generate
RUN pnpm run --filter service build

# Prepare production dependencies (isolates workspace packages & removes symlinks)
RUN rm -rf pruned
RUN pnpm --filter service --prod deploy --legacy pruned

# Production stage
FROM node:22-alpine AS production
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

COPY --from=builder /app/pruned ./

# Copy built application & prisma schema
COPY --from=builder /app/apps/service/dist ./dist
COPY --from=builder /app/apps/service/prisma ./prisma

# Generate Prisma Client in production to ensure binary compatibility
RUN pnpm add prisma@7.3.0
RUN pnpm exec prisma generate

EXPOSE 3000
CMD ["node", "dist/main.js"]