/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DashboardVisitEventIndexRouteImport } from './routes/dashboard/visit-event/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTaskIdIndexRouteImport } from './routes/dashboard/task-id/index'
import { Route as DashboardPoliExceptionIndexRouteImport } from './routes/dashboard/poli-exception/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DashboardVisitEventViewIdRouteImport } from './routes/dashboard/visit-event/view/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVisitEventIndexRoute =
  DashboardVisitEventIndexRouteImport.update({
    id: '/visit-event/',
    path: '/visit-event/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTaskIdIndexRoute = DashboardTaskIdIndexRouteImport.update({
  id: '/task-id/',
  path: '/task-id/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPoliExceptionIndexRoute =
  DashboardPoliExceptionIndexRouteImport.update({
    id: '/poli-exception/',
    path: '/poli-exception/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVisitEventViewIdRoute =
  DashboardVisitEventViewIdRouteImport.update({
    id: '/visit-event/view/$id',
    path: '/visit-event/view/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/poli-exception/': typeof DashboardPoliExceptionIndexRoute
  '/dashboard/task-id/': typeof DashboardTaskIdIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/visit-event/': typeof DashboardVisitEventIndexRoute
  '/dashboard/visit-event/view/$id': typeof DashboardVisitEventViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/poli-exception': typeof DashboardPoliExceptionIndexRoute
  '/dashboard/task-id': typeof DashboardTaskIdIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/visit-event': typeof DashboardVisitEventIndexRoute
  '/dashboard/visit-event/view/$id': typeof DashboardVisitEventViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/poli-exception/': typeof DashboardPoliExceptionIndexRoute
  '/dashboard/task-id/': typeof DashboardTaskIdIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/visit-event/': typeof DashboardVisitEventIndexRoute
  '/dashboard/visit-event/view/$id': typeof DashboardVisitEventViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/poli-exception/'
    | '/dashboard/task-id/'
    | '/dashboard/users/'
    | '/dashboard/visit-event/'
    | '/dashboard/visit-event/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/poli-exception'
    | '/dashboard/task-id'
    | '/dashboard/users'
    | '/dashboard/visit-event'
    | '/dashboard/visit-event/view/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/poli-exception/'
    | '/dashboard/task-id/'
    | '/dashboard/users/'
    | '/dashboard/visit-event/'
    | '/dashboard/visit-event/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/visit-event/': {
      id: '/dashboard/visit-event/'
      path: '/visit-event'
      fullPath: '/dashboard/visit-event/'
      preLoaderRoute: typeof DashboardVisitEventIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/task-id/': {
      id: '/dashboard/task-id/'
      path: '/task-id'
      fullPath: '/dashboard/task-id/'
      preLoaderRoute: typeof DashboardTaskIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/poli-exception/': {
      id: '/dashboard/poli-exception/'
      path: '/poli-exception'
      fullPath: '/dashboard/poli-exception/'
      preLoaderRoute: typeof DashboardPoliExceptionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/visit-event/view/$id': {
      id: '/dashboard/visit-event/view/$id'
      path: '/visit-event/view/$id'
      fullPath: '/dashboard/visit-event/view/$id'
      preLoaderRoute: typeof DashboardVisitEventViewIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPoliExceptionIndexRoute: typeof DashboardPoliExceptionIndexRoute
  DashboardTaskIdIndexRoute: typeof DashboardTaskIdIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardVisitEventIndexRoute: typeof DashboardVisitEventIndexRoute
  DashboardVisitEventViewIdRoute: typeof DashboardVisitEventViewIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPoliExceptionIndexRoute: DashboardPoliExceptionIndexRoute,
  DashboardTaskIdIndexRoute: DashboardTaskIdIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardVisitEventIndexRoute: DashboardVisitEventIndexRoute,
  DashboardVisitEventViewIdRoute: DashboardVisitEventViewIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
